import './globals.css';
import type { Metadata } from 'next';
import { StyledEngineProvider } from '@mui/material';

import ModalProvider from './context/modal-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledEngineProvider injectFirst>
          <ModalProvider>{children}</ModalProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
